system: testSystem.c dynamicArraySys.c
	gcc -o main testSystem.c dynamicArraySys.c
search: testSearch.c dynamicArraySys.c searchAlgos.c
	gcc -o main testSearch.c dynamicArraySys.c searchAlgos.c
sort: testSort.c dynamicArraySys.c sortAlgos.c
	gcc -o main testSort.c dynamicArraySys.c sortAlgos.c
clear:
	rm main
